# Generated by Django 6.0 on 2025-12-19 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0005_alter_usuario_email_equipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('prazo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('criada', 'Criada'), ('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default=('criada', 'Criada'))),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_criador_tarefa', to=settings.AUTH_USER_MODEL)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefa_equipe', to='comum.equipe')),
                ('responsaveis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsaveis_tarefa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
