# Generated by Django 6.0 on 2025-12-21 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='em_equipe',
            field=models.BooleanField(blank=True, help_text='Essa opção só dve ser marcada caso a tarefa que esteja sendo cadastrada seja pertencente à uma equipe. OBS: O usuário deve estar em uma equipe.', null=True, verbose_name='Tarefa de equipe'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(verbose_name='Descrição da tarefa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de entrega'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='responsaveis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsaveis_tarefa', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
