# Generated by Django 6.0 on 2025-12-21 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_tarefa_em_equipe_alter_tarefa_descricao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='em_equipe',
            field=models.BooleanField(blank=True, null=True, verbose_name='Tarefa de equipe'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='responsaveis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsaveis_tarefa', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
    ]
