# Generated by Django 6.0 on 2025-12-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0003_alter_tarefa_em_equipe_alter_tarefa_responsaveis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('criada', 'Criada'), ('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='criada'),
        ),
    ]
