# Generated by Django 6.0 on 2025-12-27 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0004_alter_tarefa_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='responsaveis',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, null=True, related_name='responsaveis_tarefa', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
    ]
