# Generated by Django 6.0 on 2025-12-27 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0005_remove_tarefa_responsaveis_tarefa_responsaveis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='responsaveis_tarefa', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
    ]
