# Generated by Django 6.0 on 2025-12-28 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
        ('tarefa', '0006_alter_tarefa_responsaveis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefa_equipe', to='equipe.equipe'),
        ),
    ]
