# Generated by Django 6.0 on 2026-01-03 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0001_initial'),
        ('tarefa', '0007_alter_tarefa_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacao.organizacao'),
        ),
    ]
