# Generated by Django 6.0 on 2025-12-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
    ]
