# Generated by Django 6.0 on 2025-12-21 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0005_alter_usuario_email_equipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='membros',
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros_equipe', to='comum.equipe')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
