# Generated by Django 6.0 on 2025-12-28 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0006_remove_equipe_membros_membroequipe'),
        ('equipe', '0001_initial'),
        ('tarefa', '0007_alter_tarefa_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroequipe',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros_equipe', to='equipe.equipe'),
        ),
        migrations.DeleteModel(
            name='Equipe',
        ),
    ]
