# Generated by Django 6.0 on 2025-12-31 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0007_alter_membroequipe_equipe_delete_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_membros', to=settings.AUTH_USER_MODEL),
        ),
    ]
