# Generated by Django 6.0 on 2026-01-22 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0009_alter_usuario_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_verificacao', models.CharField(max_length=6)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
