# Generated by Django 6.0 on 2026-01-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0012_tokenalterarsenha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenalterarsenha',
            name='validade',
        ),
    ]
