# Generated by Django 6.0 on 2026-01-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0013_remove_tokenalterarsenha_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenalterarsenha',
            name='validade',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
