# Generated by Django 6.0 on 2026-01-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0014_tokenalterarsenha_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenalterarsenha',
            name='token_codigo',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
