# Generated by Django 6.0 on 2026-01-03 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_alter_equipe_descricao'),
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacao.organizacao'),
        ),
    ]
