# Generated by Django 6.0 on 2026-01-07 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0003_equipe_organizacao'),
        ('organizacao', '0006_conviteorganizacao_enviado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='organizacao',
            field=models.ForeignKey(blank=True, help_text='Organização à qual a equipe pertence', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacao.organizacao', verbose_name='Organização'),
        ),
    ]
