# Generated by Django 6.0 on 2026-01-03 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('plano', models.CharField(choices=[('gratuito', 'Gratuito'), ('pago', 'Pago')], default='gratuito')),
            ],
        ),
        migrations.CreateModel(
            name='MembroOrganizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membro_organizacao', to=settings.AUTH_USER_MODEL)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizacao', to='organizacao.organizacao')),
            ],
        ),
    ]
