# Generated by Django 6.0 on 2026-01-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroorganizacao',
            name='papel',
            field=models.CharField(choices=[('responsavel_organizacao', 'Proprietário'), ('administrador', 'Administrador'), ('membro', 'Membro')], default='membro'),
        ),
    ]
