# Generated by Django 6.0 on 2026-01-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0002_membroorganizacao_papel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroorganizacao',
            name='papel',
            field=models.CharField(choices=[('proprietario', 'Proprietário'), ('administrador', 'Administrador'), ('membro', 'Membro')], default='membro'),
        ),
    ]
