# Generated by Django 6.0 on 2026-01-05 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0003_alter_membroorganizacao_papel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroorganizacao',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membroorganizacao',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='organizacao.organizacao'),
        ),
        migrations.AlterField(
            model_name='membroorganizacao',
            name='papel',
            field=models.CharField(choices=[('proprietario', 'Proprietário'), ('administrador', 'Administrador'), ('membro', 'Membro')], default='membro', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='plano',
            field=models.CharField(choices=[('gratuito', 'Gratuito'), ('pago', 'Pago')], default='gratuito', max_length=10),
        ),
    ]
