# Generated by Django 6.0 on 2026-01-06 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0004_alter_membroorganizacao_membro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteOrganizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_enviados', to='organizacao.organizacao')),
                ('usuario_convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
