# Generated by Django 6.0 on 2026-01-15 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacao', '0006_conviteorganizacao_enviado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preapproval_id', models.CharField(max_length=100, unique=True)),
                ('plano', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('authorized', 'Ativa'), ('pending', 'Pendente'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=False)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='organizacao.organizacao')),
            ],
        ),
    ]
