# Generated by Django 6.0 on 2026-01-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
